; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:4d_systems_esp32s3_gen4_r8n16]
platform = espressif32
board = 4d_systems_esp32s3_gen4_r8n16
framework = espidf
board_build.partitions = partitions.csv

build_flags =
    -fno-tree-loop-distribute-patterns
    -I src
    -I .
    -I .pio/libdeps/4d_systems_esp32s3_gen4_r8n16
    -DLV_CONF_PATH=lv_conf.h

lib_deps =
    lovyan03/LovyanGFX@^1.1.10
    lvgl/lvgl@^8.3.0
